### ISSUE TITLE
Switch from oRTP to new RTP library

### ISSUE THREAD

**Issue by njh** [njh/mast#9]
oRTP is a pain:
* The ABI keeps changing (extra parameter in rtp_session_set_local_addr, PayloadType structure, ortp_set_log_level_mask)
* The version number used by Debian/Ubuntu doesn't match the library version
* The library is now GPLed, and I would ideally like to switch MAST to something more permissive (MIT, BSD, Apache)

Requirements for replacement:
* Stable ABI
* Permissive license (MIT, BSD, Apache)
* Available on Github (making bug reports, contributions easier)
* Ideally would have a pkg-config file for easy detection
* Ideally would already be packaged up and included in Debian/Redhat/Ubuntu

Possible alternatives:
* JRTPLIB: https://github.com/j0r1/JRTPLIB (MIT License, not in Debian)
* LibRe: https://github.com/creytiv/re (BSD License, package in git repo)
* PJSIP: http://www.pjsip.org/ (Dual GPL/Commercial)
* rtp-lib: http://sourceforge.net/p/rtp-lib/
* CCRTP: https://www.gnu.org/software/ccrtp/ (GPL License)
* RTPLIB: http://www.cs.columbia.edu/irt/software/rtplib/ (Commercial License)
* Custom code?

**Comment by JaapKeuter** [comment]
The official JRTPLIB upstream is here: https://github.com/j0r1/JRTPLIB

**Comment by njh** [comment]
Version 0.5.7 of LibRe is already available in Homebrew:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/libre.rb

**Comment by paraenggu** [comment]
[GStreamer](https://gstreamer.freedesktop.org/) (LGPL) could be a suitable alternative as well. Apart from the excellent [RTP and RTSP support](https://gstreamer.freedesktop.org/documentation/rtp.html) and the availability within all major distributions, you would also gain the possibility to use other features in the future.

**Comment by njh** [comment]
A long time ago I had a bad experience with GStreamer, possibly unfairly. I should give it another look.

**Comment by njh** [comment]
Using own RTP implementation for now.
If things get more complex, I will look at using a library again.
